# Generated by Django 5.0.14 on 2026-05-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroaluno',
            name='alunos',
            field=models.ManyToManyField(related_name='registros', to='school.aluno'),
        ),
        migrations.AddField(
            model_name='registroaluno',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='school.aluno'),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='chamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='school.chamada'),
        ),
        migrations.AddField(
            model_name='registroturma',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='school.turma'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='school.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='school.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='registrochamada',
            unique_together={('chamada', 'aluno')},
        ),
        migrations.AlterUniqueTogether(
            name='chamada',
            unique_together={('data', 'turma')},
        ),
    ]
