# Generated by Django 5.0.14 on 2026-05-06 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='coordenador',
        ),
        migrations.AddField(
            model_name='turma',
            name='coordenadores',
            field=models.ManyToManyField(related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
