# Generated by Django 5.0.14 on 2026-05-07 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_turma_coordenador_turma_coordenadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaluno',
            name='lido_por',
            field=models.ManyToManyField(blank=True, related_name='registros_aluno_lidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
